Image:
  from_base: parachutes/python:3.12
  set_user: root
  run_command:
    - apt-get update && apt-get install -y build-essential ninja-build nasm clang wget unzip nvidia-cuda-dev nvidia-cuda-toolkit pkg-config libx264-dev git python3-pip python3-venv
  set_user: root
  run_command:
    - uv pip install meson
  set_user: root
  run_command:
    - wget https://github.com/FFmpeg/nv-codec-headers/archive/876af32a202d0de83bd1d36fe74ee0f7fcf86b0d.zip && unzip 876af32a202d0de83bd1d36fe74ee0f7fcf86b0d.zip && cd nv-codec-headers-876af32a202d0de83bd1d36fe74ee0f7fcf86b0d && make && make install && cd / && rm -rf nv-codec-headers-* 876af32a202d0de83bd1d36fe74ee0f7fcf86b0d.zip
    - git clone --depth 1 --branch 1.4.2 https://code.videolan.org/videolan/dav1d.git && cd dav1d && mkdir build && cd build && meson setup .. --default-library=static --buildtype release && ninja && ninja install && ldconfig && cd / && rm -rf dav1d
    - export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" && git clone https://github.com/FFmpeg/FFmpeg ffmpeg && cd ffmpeg && git reset --hard 33b215d1554a14e87416a24f8e6034312e629af7 && ./configure --enable-gpl --enable-libx264 --enable-libdav1d --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags="-I/usr/local/cuda/include" --extra-ldflags="-L/usr/local/cuda/lib64" --disable-static --enable-shared --nvccflags="-gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75 -O2" && make -j && make install && ldconfig && cd / && rm -rf ffmpeg
  set_user: chutes
  run_command:
    - uv pip install --upgrade setuptools wheel
    - uv pip install huggingface_hub==0.19.4 minio
  set_workdir: /app

NodeSelector:
  gpu_count: 1
  min_vram_gb_per_gpu: 16

Chute:
  shutdown_after_seconds: 600
  concurrency: 2
  max_instances: 5
  scaling_threshold: 0.5