MONGO_URI: "mongodb://localhost:27017/?replicaSet=rs0"
DB_NAME: "vidaio"
COLLECTION_NAME: "videos"

VIDEO_DIR: "/root/vidaio/videodb/original/"
TEST_VIDEO_DIR: "/root/vidaio/videodb/test/"
VMAF_SCORE_THRESHOLD: 60

HASH_SEARCH_V2_THREADS: 8
HASH_SEARCH_V2_COARSE_UNIT: 4
HASH_SEARCH_V2_COARSE_INTERVAL: 3

MIN_VIDEO_LEN: 25
MAX_VIDEO_LEN: 50
PEXELS_CHECK_INTERVAL: 3600 # 1 hour

SEARCH_SERVICE_HOST: "localhost"
SEARCH_SERVICE_PORT: 5005

PEXELS_API_KEYS:
  - UI7HcVZyfFTW7lB23zwZXJXF08PRi1axgFWeSkc6tQwlZ9qe2cntYAO6
  - dHtCvrfkrqUL61rm2vwsaYDTjBa5SYhNfRZOTQch3MIYUh6USLlbZp5x
  - GAGkAyaCbzFzzqA6RGmpdRYHfqW8zqzOHsUfrUAHXVN0fOxUqxjWsQxO
  - EG8P4tCOTMR66MJVAPG86joECVEXjoQ2wqcDGszty7Gbke7p1re8InOg
  - DpOsgYhUKjh1nOM8cC5GO7dBvHj8bUImome5XyHJ8n1kXuwASePgktUT
  - ADA6cXrbeQUk0wznx7ZNOkuV32vUd0YTGFGJ1vPOT30elcE0kTfQwLQ7
  - yJkDd2z1yj9K0dlND1aCpDogQrv9kSiqOErDRzu01yKi4C9Qz6edRbXT
  - hRj8vmUpCPdNXVp1iByJH9R4jRXGjr7bJB0hsunIZBKjVqRihfzwk287
  - IoiJ71emD8qwC9ytlESKhVfAkQ9wDqJ77HosJyRRP6fozRYVXBy3SlJh
  - RAl4D8qO0UxzGoslby6wQQM00nDUkFYPl9AXHhQsotZmwu5zBBi4hnzC
  - 5z5wt80ryHBY8KVQKg63ryZWKpktfEc0SiBmq29EilHfJfW0SPN5pRZZ
  - SoGuadzkjVApDZpQp8u6M8Hyezp59Fd43LNUgq6vA1PkcjAXO9qdJILf
  - 7Qtj9CAP7kCthFGoCSnLoMpK7fcZ0rW4ysaBZt1MmnHPqMpqDaWhQ9q6
  - hmqIfYYjwMKn3SrixMuBzH6p9NeObYZIg7HXVGB7Q8qrPMb1EDqrSAIS
  - 1wTQKEIQcdmNXqRFU08wXArpYMDD3Ry4h0MxgueJeQ5IgYDtU5BG0mLy
  - 7CjCc4eao8pgtk4fdZsRojAuTXDpKVoNXZDNqL5Lerh9G97nEi42z7UT
  - sc1QAfUX1g4IzvayQ0hoZaGlcg8GzhX0RM9IIYKwfFJ7tZXB0lMNhlcc
  - 1Yn5oo3EZ9VrH2iNC4Ec0zhcAczDAbFxNjaauqKP2Vaye9LXdmx9tQcE
  - MhFFeroXlN7CTCAF01OcRCqAjGbk4vi2DZD5nsLjZCWnbm02vZEGq0Nc
  - 1sEQixeFjYbSPS882vfCOSRMACiym0yEbyk9jMyjoN7liF8GjvqcDHKB
  - YvPxaW5v0CImA3JRynsTJEMlDIxp8S0WG1MjqR5KJOgVHRppwabZhGj4
  - 0zhqp0oMCJgJfXIQvjCBQVe2ZvJwV2Sw4fgF89GOwy0oOmfwXCp6btar
  - 95IcS244axkCrmuVecHs0d9Tsuh3ZdPooJzH6sZo5uAnsFTlmKdF0VcA
  - ApKTlZtHEiiVHQFpIrjQx3G2p2uwSsPAzTuLVcFKgw5zIFb6iWZ5REK3
  - 5EqDtksGYJCCplVjPm6QzybUGhj3XSlOIoojOILyxX06r9tBUQFgiTud
  - 8WJ8WYXfQWTlEHcK80cka0V3apW5MX0lYKo45OtFDoU0vk3tJVumQgHZ
  - qUOznmhjZx4bMxlfaLKVJfEUaoGoSCJCrmDtftPAeWKDfLkIaCtqiTZk
  - 1iW2ZXpU2KDlWk843XJnnJPbDmGgTM3kINdDW718lggvShTp8SiAuUAf
  - a5Ez4pVpXJhg10myuFuuYfK7ESbnL6w96p3toBRBRCbT8KAfwILPGwEK
  - 7mjhvtZJry21hDkC0QLTP5iFwKq0QcbQ55KYXzdxtC3tsVoiZ3Ps4UGv
  - LJsJjub9Dy4j4ajfLX9eBeLJjeSVeeq3UrxJhuQq4yUAbhsfntewo3OE
  - AUh8RiOSrGbzPK1R6VTuCap8VUw4C4LOaytk9ButhmCuhaiOI6th3ySK
  - QlJTz1EydNXrqB04ACoY7gEWhYccIKBROPvFZn2EuQa0o6CTHb8Om1pv
  - nOwV52UoH1Bx845gXSw7lUsEU7JmMMsGepiYkRrGvbGasdpsL4XQTmDU
  - AZcZ8CXla6GDwsgHtLSro43Q4vjUb41mSl7wwMfWtn8ffWiLK7keOh0l
  - Ta9uaw6sdQu6JZdk7G5EuxUYQWsV9cwAfZPsNjKB6MIt1EXXpyH0NPnB
  - RqkKigYSm2srvywiPUSrbsHj3qHVsAPfeSSTvB4yz5tgtI8VGS9CcKL8
  - 3wsMjsXv7ftJpFRNKDqOf2QcUUX3kNEx0qZQtYtNCl95sT1I1d1QUifz
  - Nh2rLkPFNauMEgdSwvNKg3CSl2RQQooq3yrQ0kh4ZOu0JGvx2yglc1sH
  - xBw2Pu6qPVEEOlHsuOq0eZquaU6XsUVui8nm0mqziHjSghjKwK5bIK1t
  - SpcwReU404wKf9lL68MchNmrX2ZNtDaSRc5Au5oPPBK9FJdtWYFuctgQ
  - PwfJjREDRCPJvVhtRSChH7P4rITz1qTBD0DprQn0M7S4WoldZcR9BD8e
  - Z0e46gGHF2BW2OZ7vpHQwTnuQ6NouIx43V8b89d2fawYWsILZjthLVXI
  - LUoAJf3CD6IIVyS1qekg7Tl65SOaBHyr9xcKMiM08kN5AKLgYyJPviNd
  - WUS4YGn17i5yQhy27oKZyT4UKpW9BmzZXtMhFK6DdEHwa0XYn9fF4JAn
  - 8dzkLDSEo6Z6lWLxxnBPhA0kumyWdetb5puq9y2esFkIBD2WS4BeTfR1
  - ZByicK2EFUHJ5Y1OMs5rN0jxgXPFhgqRLuxzPxZ0agWFbmowMqs9JU3C
  - zjP2PtLCVo40cOqXCCiKBWkOEXrkBymP4eSMq3uZKMBox7QVpE4w2AQF
  - KTZHB7uZx58n8BLE23QUTkd6Os7huD5vuB60PkpxvNk6gJkM7wdfNriN
  - 4ykoN5gygyWjQ9OZkNqSfVG0XFIgWORrJFc3pJrAcuPSVKnN4G0qKmS4
  - Hr7vQTTceNDmGOuFiADPVZg0ITLSjIWzqHlH8ulG1GWuc9vq33ga03Eu
  - u29jD9N3XijeltoDgMaBKsx25S1RFuGaSmSnHwCb3fBHybpvF7xYBKz7
  - 1ajHAlPwl5OJahbq7TAYTZKWR7CzNGvOeaEDPtovm1oqtTEwfi7Ua2jA
  - OLv8J0RfL3iNt2tkw88PZ7FoM704JJXjshqGx5WKi0zejtV8s0PR4Q42
  - WD9OjZcFWztgC6no5AQksf5ixmdrW1EfLqpiYqxOWozhLX2DKzCYVkcO
  - IVVpGOKxM8vkqJQGziB7PN9FX8WhxWAFlusWe9UvMyPgPpMcAkNR2YNK
  - nFfgK7tYZqdcBKPOQ3xhg1MNsofTa9KoWHfRtqFgtPT9TOMfg6uqV07R
