services:
  compression:
    build: ./compression
    ports:
      - "8004:8004"
    volumes:
      - video-tmp:/tmp/organic-proxy
      - /var/run/docker.sock:/var/run/docker.sock

  upscaling:
    build: ./upscaling
    ports:
      - "8003:8003"
    volumes:
      - video-tmp:/tmp/organic-proxy
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  video-tmp:
