Image:
  from_base: parachutes/python:3.12
  set_user: root
  run_command:
    - apt-get update && apt-get install -y ffmpeg curl libvulkan1
    - curl -L -o /usr/local/bin/video2x https://github.com/k4yt3x/video2x/releases/download/6.4.0/Video2X-x86_64.AppImage && chmod +x /usr/local/bin/video2x
  set_user: chutes
  run_command:
    - uv pip install --upgrade setuptools wheel
    - uv pip install huggingface_hub==0.19.4 minio
  set_user: chutes
  set_workdir: /app

NodeSelector:
  gpu_count: 1
  min_vram_gb_per_gpu: 16

Chute:
  shutdown_after_seconds: 600
  concurrency: 1
  max_instances: 3
  scaling_threshold: 0.5
